version: '3.8'

services:
  redis:
    image: redis:latest
    command: redis-server --port 6380
    ports:
      - '6380:6380'
    healthcheck:
      test: ['CMD', 'redis-cli', '-p', '6380', 'ping']
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 3657
    ports:
      - '3657:3657'
    volumes:
      - ./key.json:/app/key.json
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_URL=redis://redis:6380/0
      - CELERY_BROKER_URL=redis://redis:6380/0
      - CELERY_RESULT_BACKEND=redis://redis:6380/0

  celery_worker:
    build: .
    command: celery -A app.worker.celery_app worker --loglevel=info --concurrency=50
    volumes:
      - ./key.json:/app/key.json
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_URL=redis://redis:6380/0
      - CELERY_BROKER_URL=redis://redis:6380/0
      - CELERY_RESULT_BACKEND=redis://redis:6380/0

volumes:
  postgres_data:
