"""Adding youtube link col

Revision ID: b2598f737b6d
Revises: 3e98b8300152
Create Date: 2024-08-18 12:37:27.139153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2598f737b6d'
down_revision: Union[str, None] = '3e98b8300152'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('youtube_link', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'youtube_link')
    # ### end Alembic commands ###
