"""adding folder and user id on metadata

Revision ID: daa4d6319534
Revises: cc2bd32b1d9f
Create Date: 2024-08-25 14:15:37.046502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daa4d6319534'
down_revision: Union[str, None] = 'cc2bd32b1d9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
