"""

Revision ID: e0c5dda9fcb2
Revises: b4a0a6a94c2a
Create Date: 2024-08-25 14:07:59.709864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0c5dda9fcb2'
down_revision: Union[str, None] = 'b4a0a6a94c2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note_metadata', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('note_metadata', sa.Column('folder_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'note_metadata', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'note_metadata', 'folders', ['folder_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'note_metadata', type_='foreignkey')
    op.drop_constraint(None, 'note_metadata', type_='foreignkey')
    op.drop_column('note_metadata', 'folder_id')
    op.drop_column('note_metadata', 'user_id')
    # ### end Alembic commands ###
