"""

Revision ID: e2f0353d8e44
Revises: 96dbf61620e1
Create Date: 2024-09-08 00:22:55.386017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2f0353d8e44'
down_revision: Union[str, None] = '96dbf61620e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('transaction_receipt', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'transaction_receipt')
    # ### end Alembic commands ###
